apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: resume
  name: resume
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resume
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: resume
    spec:
      containers:
      - image: wgleich/resume:latest
        name: resume
        resources: {}
status: {}
