apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: defn.ly
  labels:
    app: defn.ly
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: node
          image: wgleich/defn-ly:latest
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: defn-ly
spec:
  type: LoadBalancer
  selector:
    app: defn.ly
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080