bases:
  - ../kustomize
namePrefix: dev-
namespace: dev
commonLabels:
  environment: development

patchesJson6902:
  - target:
      group: networking.k8s.io
      version: v1beta1
      kind: Ingress
      name: resume-ingress
    path: ing-patch.yaml

images:
  - name: wgleich/resume
    newName: wgleich/resume
    newTag: "latest"
