version: 2
jobs:
  build:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t wgleich/defnly:circleci .
      - run: echo "A first hello"
      - run:
          name: Build Docker image
          command: docker push -t wgleich:circleci .